### ISSUE TITLE
Error when checking input: wrong input shape

### ISSUE THREAD

**Issue by VGalata** [pacific-2020/pacific#8]
Hello,

First of all, thanks for the great tool!

Unfortunately, I have encountered an issue when trying to run `PACIFIC` on one of our samples:

Error message:
```
ValueError: Error when checking input: expected embedding_1_input to have shape (142,) but got array with shape (1,)
```

Command line:
```bash
python /path/to/PACIFIC.py -i my.fq -m path/to/pacific.h5 -t /path/to/model/tokenizer.01.pacific_9mers.pickle -l /path/to/model/label_maker.01.pacific_9mers.pickle -o output/folder/ -f fastq
```

The input FASTQ file contains paired reads and single-end reads (all three FASTQ files were just concatenated).

Version: `075fb55`

`conda` env. YAML:
```yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.6
  - numpy=1.18.1
  - tensorflow=2.2.0
  - keras=2.3.1
  - pandas=1.0.1
  - scikit-learn=0.21.3
  - biopython=1.76
```

Thanks in advance!

Best,
Valentina
